name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test1
      id: test1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test1
        setup-command: sudo apt update && sudo apt install octave  && sudo apt install
          octave-dev && sudo apt install octave-statistics
        command: octave --eval "pkg install -forge struct; pkg install -forge io;
          pkg install -forge optim; [blendA1, blendB1] = exercicio2(1); [blendA2,
          blendB2] = exercicio2(8); assert((abs((blendA1 + blendB1) - 66.667) < 0.1)
          || (abs((blendA2 + blendB2) - 65) < 0.1))"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
      with:
        runners: test1
